language: cpp

sudo: required

install: |
  cd "$TRAVIS_BUILD_DIR"
  bash -x ./configure -t

script: |
  cd "$TRAVIS_BUILD_DIR"
  bash -x ./build -j 16 &>/dev/null
  bash -x ./run -e 'init=/poweroff.out' -n
