language: cpp

sudo: required

install: |
  cd "$TRAVIS_BUILD_DIR"
  bash -x ./download-dependencies --travis

script: |
  cd "$TRAVIS_BUILD_DIR"
  # --nproc: I'm unable to install nproc on Travis.
  # TODO why? Is part of coreutils in Ubuntu 16.04:
  # http://manpages.ubuntu.com/manpages/trusty/man1/nproc.1.html
  # which ./download-dependencies is installing.
  #
  # awk: without it, too much stdout (4Mb max)
  # If we ignore stdout: Travis kills job because it spent
  # too long without any new stdout.
  bash -x ./build-qemu --nproc 16 |& awk 'NR % 1000 == 0'
  bash -x ./build-buildroot --nproc 16 |& awk 'NR % 1000 == 0'
  bash -x ./run --kernel-cli 'init=/poweroff.out'
